<a href="https://colab.research.google.com/github/Elimirage/digital_image_processing_24vvim1/blob/main/lab1/digital_image_processing_lb1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Лабораторная работа №1**

*   Группа: 24ВВИм1
*   Юмаева Эльмира



Задание: Необходимо средствами библиотеки numpy сгенерировать два массива со случайными значениями, найти одинаковые и сохранить в третий массив.

In [47]:
!pip3 install numpy

In [48]:
import numpy as np

# **Одномерные массивы**

Создаем массив, заполненный случайными значениями:
rnd = np.random.default_rng() -- создаем генератор
rnd.integers(min, max, n) -- возвращаем массив размерности n случайных равномерно расспределенных целых чисел, где x ∈ [min, max)
Создаем два случайно заполненных массива и один пустой список, для того, чтобы заполнить их повторяющимися элементами. Выводим на экран массивы

In [60]:
rnd = np.random.default_rng()
a = rnd.integers(0, 100, 30)
b = rnd.integers(0, 100, 30)
c = []
print('Первый массив:',a)
print('Второй массив:',b)

Первый массив: [72  0 97 86 89 57 78 40 21 71 38 55 68 20 20 22 66 14 72 27 51 22 29 49
 44 87 25 62 55 15]
Второй массив: [52 60 15 37 46 43 20 37 32 69 25 28 11 67 77 37 65  7 44 49 94 82 17 69
 84 14  8 27 36 72]


В цикле проверяем находится ли i-тый элемент во втором массиве, есла да - то добавляем его в список. В конце преобразуем нашсписок в массив и выводим на экран. В результате получем массив с повторяющимися элементами

In [50]:
for i in range(len(a)):
    if a[i] in b:
        c.append(a[i])
c = np.array(c)
print(c)

[97 41 76 49 60]


Если же мыхотим получить только уникальные элементы в новом массиве, то используем функцию set, котрая оставляет только уникальные значения и пересечение

In [51]:
c = np.array(list(set(a) & set(b)))
print(c)

[97 41 76 49 60]


# **Многомерные массивы**

Сгенертровали многомерные массивы

In [84]:
a2 = np.random.randint(0, 57, size=(5, 4))
b2 = np.random.randint(0, 57, size=(5, 4))
print('Первый массив:\n', a2)
print('\nВторой массив:\n', b2)

Первый массив:
 [[44 30 24 38]
 [23 47  1  7]
 [36 33 42 33]
 [19 56 24 29]
 [42 38 45 12]]

Второй массив:
 [[47 55 51 34]
 [ 4 14 26 15]
 [11 10 54 41]
 [ 6 43 45 37]
 [ 3 17 21  2]]


Преобразовали их в одномерный массив, для того,чтобы найти одинаковые элементы, как в первом случае


In [85]:
a2 = a2.reshape(-1)
b2 = b2.reshape(-1)
print(a2,b2)

[44 30 24 38 23 47  1  7 36 33 42 33 19 56 24 29 42 38 45 12] [47 55 51 34  4 14 26 15 11 10 54 41  6 43 45 37  3 17 21  2]


In [86]:
c2 = np.array(list(set(a2) & set(b2)))
print(c2)

[45 47]
